# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    # You can test your matrix by printing the current Go version
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: |
        go install github.com/a-h/templ/cmd/templ@latest

    - name: Build Templ
      run: templ generate

    - name: Build Core
      run: go build -v ./...

    - name: Use Node.js for assets
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - run: cd assets/js && npm ci
    - run: cd assets/js && npm run esbuild
    - run: cd assets/js && npm run tailwindcss

    - name: Test application
      run: go test -v ./...

